#=====================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Use Releases file to packaging
#=====================================================================================

name: Packaging NanopiK2_PLUS

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "lede"
        type: choice
        options:
          - lede
      openwrt_board:
        description: "Select device board"
        required: false
        default: "s905"
        type: choice
        options:
          - s905
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "6.1.14"
        #type: choice
        options:
          - 5.10.160
          - 5.15.85
          - 6.1.13
          - 6.1.14
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set the kernel repository"
        required: false
        default: "https://github.com/ophub/kernel/tree/main/pub"
      openwrt_size:
        description: "Set the rootfs size(Unit: MiB)"
        required: false
        default: "1024"
      openwrt_armvirt_url:
        description: "armvirt_url"
        required: true
        default: "https://github.com/haiibo/OpenWrt/releases/download/ROOTFS_PLUS/openwrt-armvirt-64-default-rootfs.tar.gz"      

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "OPENWRT_RELEASE=${{ inputs.source_branch }}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Download OpenWrt Armvirt firmware
        id: down
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          armvirt_tarfile_path="openwrt/bin/targets/armvirt/64"
          
          [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}

          wget -q -P ${armvirt_tarfile_path} ${{ inputs.openwrt_armvirt_url }}
          [[ "${?}" -ne "0" ]] && echo "The armvirt file download failed!" && exit 1

          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Build OpenWrt firmware [ ${{ env.OPENWRT_RELEASE }} ]
        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
        uses: NicoChiGu/amlogic-nanopik2-openwrt@main
        with:
          openwrt_path: openwrt/bin/targets/*/*/*rootfs.tar.gz
          openwrt_board: ${{ inputs.openwrt_board }}
          openwrt_kernel: ${{ inputs.openwrt_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          openwrt_size: ${{ inputs.openwrt_size }}
          gh_token: ${{ secrets.GH_TOKEN2 }}

      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: NanopiK2_${{ inputs.openwrt_kernel }}_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN2 }}
          body: |
            ## Openwrt NanopiK2 固件
            ### 固件信息
            #### 固件分区: boots:**255Mb**/Rootfs:**1024Mb**
            默认IP: 192.168.1.1
            默认用户名: root
            默认密码: password
            默认WIFI SSID: OpenWrt
            默认密码: 无安全
            首次扩容TF操作: 使用串口/键盘+HDMI/网页TTYD 运行 openwrt-tf 并阅读提示 确认后按"Y"
      
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 15
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN2 }}
